apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: k3y0puqor-python
  janus-idp.io/tekton: k3y0puqor-python
  backstage.io/kubernetes-id: k3y0puqor-python
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: k3y0puqor-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
